Добавление в компоненты подписок на события DOM
adaptedbee/react-underhood-boilerplate pull request #3
Opened 2020-05-07 13:26 UTC by adaptedbee

2020-05-14 11:21 UTC, oceandrama approved these changes

2020-05-14 11:21 UTC, oceandrama commented on samples/App.jsx
> +        <br />
Отступы лучше делать с помощью стилей. Можно прямо инлайн в тег

2020-05-14 11:21 UTC, oceandrama commented on samples/App.jsx
> +      sortString.includes(letter.toLowerCase())
Может, тогда строку из инпута в `upperCase` перевести, чтобы не переводить каждый символ?

2020-05-14 11:21 UTC, oceandrama commented on samples/App.jsx
> +      if (sortString.indexOf(a) < sortString.indexOf(b)) {
Можно просто `sortString.indexOf(a) - sortString.indexOf(b)`

2020-05-14 11:21 UTC, oceandrama commented on samples/App.jsx
> +  handleTextInput(event) {
Я бы вынес в отдельную функцию и написал тесты, чтобы продемонстрировать логику работы. Так ревьюверу будет гораздо проще разобраться в том, как работает код

2020-05-14 11:28 UTC, oceandrama requested changes

2020-05-14 11:28 UTC, oceandrama commented on samples/App.jsx
> +  handleTextInput(event) {
Потому что сейчас она работает неправильно
На входных данных (["а", "б", "в", "г", "д"], "гба") должно получиться ["г","б","в","а","д"]

2020-05-14 13:21 UTC, adaptedbee commented on samples/App.jsx
> +  handleTextInput(event) {
@oceandrama Почему?
Сначала буквы перестраиваются в соответствии с вхождением в строку - "гба"
Оставшиеся сохраняют прежний порядок - "вд"
Итого "гбавд"

2020-05-14 18:31 UTC, oceandrama commented on samples/App.jsx
> +  handleTextInput(event) {
Ну, в том-то и дело, что оставшиеся буквы не остались на своих местах. "в" была на 3 месте, а стала на 4
Первый шаг алгоритма верный - нужно взять буквы в нужном порядке, но вставить их нужно не в начало строки, а на те места, где они стояли до этого

2020-05-15 11:09 UTC, adaptedbee commented on samples/App.jsx
> +        <br />
Обновил

2020-05-15 11:10 UTC, adaptedbee commented on samples/App.jsx
> +      sortString.includes(letter.toLowerCase())
Обновил

2020-05-15 11:10 UTC, adaptedbee commented on samples/App.jsx
> +      if (sortString.indexOf(a) < sortString.indexOf(b)) {
Обновил

2020-05-15 11:11 UTC, adaptedbee commented on samples/App.jsx
> +  handleTextInput(event) {
Обновил

2020-05-21 11:02 UTC, merged